line-length = 120
include = ["*.py"]
output-format = "concise"

[lint]
select = ["ALL"]
ignore = ["E402",  
          "S101", 
          "PT027", 
          "PT009", 
          "D203", 
          "D213",
          "TRY300",
          "COM812" ] 

[lint.pylint]
max-args = 10
max-returns = 12
max-branches = 20
max-statements = 100

[lint.mccabe]
max-complexity = 24